# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47ee0cd9cdb45dddfa6036639dc9ef0de3ac27cfb0e5d9c2101287bf4a5453e92a4e160ae142be68b344b8c9478fa6347496621de38fb81bc07e39eb465dce75

test:
  secret_key_base: 5d22e733702e832138ca0289c0442c78359451f7c4489aa35f34c7646faa7116b3d5282a0e414686ab6c1de11b5586e4e41c21d4593837abc0e945820f065655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
